### ISSUE TITLE
TODO deploy v2

### ISSUE THREAD

**Issue by SkrzypMajster** [SkrzypMajster/text-statistics#2]
- [x] Use colections in model,
- [x] Use standard annotations,
- [x] Use for-each loop,
- [x] lambda expression (with defined interface),
- [x] Write unit tests for every public method in model class (except constructors, getters and setters), - tests should include correct, incorrect and borderline situations for each unit tested,
- [x] Implement result counter in getGramStatistics method

**Comment by SkrzypMajster** [comment]
In 4th point I decided to implement lambda expressions
