### ISSUE TITLE
TODO deploy v3

### ISSUE THREAD

**Issue by SkrzypMajster** [SkrzypMajster/text-statistics#6]
- [ ] Division app into 2 small apps: client app (with view class) and TCP server (includes application model),
- [ ] Port configuration (on server app) and port and server address (client app) in properties file,
- [ ] Communication between the client and the server should be implemented in separate classes and package (except for the view and model) in each project,
- [ ] Object of the model class should be created once in the entire server lifecycle,
- [ ] Implement own communication protocol, in which parameters for calculations are passed, and then calculations are started,
- [ ] The server should recognize the incorrect order of protocol commands,
- [ ] Each client command should be confirmed by the server with a one-line message starting with the response code, allowing the client to recognize if the server has accepted the command,
- [ ] Provide support for the HELP command, sending a one-line list of available commands with their syntax for testing the server from the universal client level (for ex. telnet, putty),
- [ ] Exceptions on the server side should be reported with appropriate messages on the client app,
- [ ] Handling exceptions during communication,
